export const RELEASE1_REPOSITORIES = Symbol("RELEASE1_REPOSITORIES");
export const RELEASE4_REPOSITORIES = Symbol("RELEASE4_REPOSITORIES");
export const RELEASE8_REPOSITORIES = Symbol("RELEASE8_REPOSITORIES");
export const RELEASE9_REPOSITORIES = Symbol("RELEASE9_REPOSITORIES");
export const RELEASE10_REPOSITORIES = Symbol("RELEASE10_REPOSITORIES");
export const RELEASE11_REPOSITORIES = Symbol("RELEASE11_REPOSITORIES");
export const RELEASE12_REPOSITORIES = Symbol("RELEASE12_REPOSITORIES");
