import { getFinanceExportJob } from "../../../../../../lib/api";
import {
  Card,
  DataTable,
  EmptyState,
  Pill,
  toneForStatus,
  WorkspaceHeader
} from "../../../../ui";

type ExportDetailPageProps = {
  params: Promise<{ exportJobId: string; organizationId: string }>;
};

export default async function ExportDetailPage(props: ExportDetailPageProps) {
  const { exportJobId, organizationId } = await props.params;
  const detail = await getFinanceExportJob(organizationId, exportJobId);
  const job = detail.exportJob;

  return (
    <>
      <WorkspaceHeader
        eyebrow="Export Detail"
        subtitle="Queued finance artifacts generated by the worker from Release 9 reporting projections."
        title={job.id}
      />
      <div className="split-grid">
        <Card title="Job Summary">
          <div className="detail-grid">
            <div className="detail-item">
              <span className="muted">Status</span>
              <Pill tone={toneForStatus(job.status)} value={job.status} />
            </div>
            <div className="detail-item">
              <span className="muted">Started</span>
              <strong className="mono">{job.startedAt ?? "not started"}</strong>
            </div>
            <div className="detail-item">
              <span className="muted">Finished</span>
              <strong className="mono">{job.finishedAt ?? "not finished"}</strong>
            </div>
          </div>
        </Card>
        <Card title="Filters">
          <pre className="code-block">{JSON.stringify(job.filters, null, 2)}</pre>
        </Card>
      </div>
      <Card title="Artifacts">
        {job.artifacts.length === 0 ? (
          <EmptyState body="The worker has not persisted any export artifacts for this job yet." />
        ) : (
          <DataTable headers={["Filename", "Format", "Size", "Preview"]}>
            {job.artifacts.map((artifact) => (
              <tr key={artifact.id}>
                <td>{artifact.filename}</td>
                <td>{artifact.format}</td>
                <td>{artifact.sizeBytes}</td>
                <td>
                  <pre className="code-block">
                    {artifact.body.slice(0, 1200)}
                    {artifact.body.length > 1200 ? "\n..." : ""}
                  </pre>
                </td>
              </tr>
            ))}
          </DataTable>
        )}
      </Card>
    </>
  );
}
