import { z } from "zod";

import type { EntityId, IsoTimestamp, JsonObject } from "./primitives";

export const auditActionSchema = z.enum([
  "AUTH_LOGOUT",
  "AUTH_NONCE_ISSUED",
  "AUTH_SESSION_VERIFIED",
  "APPROVAL_MUTATION_BLOCKED",
  "APPROVAL_POLICY_CREATED",
  "APPROVAL_REQUEST_CREATED",
  "APPROVAL_STEP_DECIDED",
  "COUNTERPARTY_CREATED",
  "COMPLIANCE_CASE_ASSIGNED",
  "COMPLIANCE_CASE_CREATED",
  "COMPLIANCE_CASE_NOTE_ADDED",
  "COMPLIANCE_CASE_STATUS_UPDATED",
  "COMPLIANCE_CHECKPOINT_CREATED",
  "COMPLIANCE_CHECKPOINT_DECIDED",
  "DEAL_MILESTONE_DISPUTE_ARBITRATOR_ASSIGNED",
  "DEAL_MILESTONE_DISPUTE_DECISION_SUBMITTED",
  "DEAL_MILESTONE_DISPUTE_OPENED",
  "DRAFT_DEAL_COUNTERPARTY_WALLET_UPDATED",
  "DEAL_VERSION_ACCEPTANCE_CREATED",
  "DEAL_VERSION_COUNTERPARTY_ACCEPTANCE_CREATED",
  "DEAL_MILESTONE_RELEASE_REQUESTED",
  "DEAL_MILESTONE_REFUND_REQUESTED",
  "DEAL_MILESTONE_SETTLEMENT_EXECUTION_TRANSACTION_RECONCILIATION_UPDATED",
  "DEAL_MILESTONE_SETTLEMENT_EXECUTION_TRANSACTION_STALE_PENDING",
  "DEAL_MILESTONE_SETTLEMENT_EXECUTION_TRANSACTION_SUBMITTED",
  "DEAL_MILESTONE_SETTLEMENT_EXECUTION_TRANSACTION_SUPERSEDED",
  "DEAL_MILESTONE_SETTLEMENT_EXECUTION_PREPARED",
  "DEAL_MILESTONE_REVIEW_DEADLINE_EXPIRED",
  "DEAL_MILESTONE_REVIEW_APPROVED",
  "DEAL_MILESTONE_REVIEW_REJECTED",
  "DEAL_MILESTONE_SUBMISSION_CREATED",
  "DRAFT_DEAL_ACTIVATED",
  "DRAFT_DEAL_CUSTODY_STATE_RECONCILED",
  "DEAL_VERSION_CREATED",
  "DRAFT_DEAL_CREATED",
  "FILE_CREATED",
  "FUNDING_TRANSACTION_RECONCILIATION_UPDATED",
  "FUNDING_TRANSACTION_STALE_PENDING",
  "FUNDING_TRANSACTION_SUPERSEDED",
  "FUNDING_TRANSACTION_SUBMITTED",
  "COST_CENTER_CREATED",
  "ORGANIZATION_CREATED",
  "ORGANIZATION_INVITE_REVOKED",
  "ORGANIZATION_INVITE_ACCEPTED",
  "ORGANIZATION_INVITE_CREATED",
  "ORGANIZATION_MEMBER_REMOVED",
  "ORGANIZATION_MEMBER_ROLE_UPDATED",
  "OPERATOR_ALERT_ACKNOWLEDGED",
  "OPERATOR_ALERT_RESOLVED",
  "PROTOCOL_PROPOSAL_DRAFT_CREATED",
  "FINANCE_EXPORT_CREATED",
  "FINANCE_EXPORT_COMPLETED",
  "FINANCE_EXPORT_FAILED",
  "STATEMENT_SNAPSHOT_CREATED",
  "TEMPLATE_CREATED"
]);
export type AuditAction = z.infer<typeof auditActionSchema>;

export const auditEntityTypeSchema = z.enum([
  "APPROVAL_POLICY",
  "APPROVAL_REQUEST",
  "APPROVAL_REQUEST_STEP",
  "COMPLIANCE_CASE",
  "COMPLIANCE_CASE_NOTE",
  "COMPLIANCE_CHECKPOINT",
  "COUNTERPARTY",
  "COST_CENTER",
  "DEAL_MILESTONE_DISPUTE",
  "DEAL_MILESTONE_DISPUTE_ASSIGNMENT",
  "DEAL_MILESTONE_DISPUTE_DECISION",
  "DEAL_MILESTONE_SETTLEMENT_EXECUTION_TRANSACTION",
  "DEAL_VERSION_ACCEPTANCE",
  "DEAL_VERSION_COUNTERPARTY_ACCEPTANCE",
  "DEAL_VERSION",
  "DEAL_MILESTONE_SETTLEMENT_REQUEST",
  "DEAL_MILESTONE_REVIEW",
  "DEAL_MILESTONE_SUBMISSION",
  "DRAFT_DEAL",
  "FILE",
  "FUNDING_TRANSACTION",
  "ORGANIZATION",
  "ORGANIZATION_INVITE",
  "ORGANIZATION_MEMBER",
  "OPERATOR_ALERT",
  "PROTOCOL_PROPOSAL_DRAFT",
  "SESSION",
  "FINANCE_EXPORT_JOB",
  "FINANCE_EXPORT_ARTIFACT",
  "STATEMENT_SNAPSHOT",
  "TEMPLATE",
  "USER",
  "WALLET"
]);
export type AuditEntityType = z.infer<typeof auditEntityTypeSchema>;

export const listAuditLogsParamsSchema = z.object({
  entityId: z.string().trim().min(1),
  entityType: auditEntityTypeSchema
});
export type ListAuditLogsParams = z.infer<typeof listAuditLogsParamsSchema>;

export interface AuditLogEntry {
  action: AuditAction;
  actorUserId: EntityId | null;
  entityId: EntityId;
  entityType: AuditEntityType;
  id: EntityId;
  ipAddress: string | null;
  metadata: JsonObject | null;
  occurredAt: IsoTimestamp;
  organizationId: EntityId | null;
  userAgent: string | null;
}

export interface ListAuditLogsResponse {
  auditLogs: AuditLogEntry[];
}
