ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'GAS_POLICY_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'GAS_POLICY_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SPONSORED_TRANSACTION_REQUEST_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'WALLET_PROFILE_UPDATED';

ALTER TYPE "AuditEntityType" ADD VALUE IF NOT EXISTS 'GAS_POLICY';
